version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    labels:
      - "dependencies" 
      - "auto-merge"
    commit-message:
      prefix: "chore(deps)"
    ignore:
      - dependency-name: "*"
        update-type: "version-update:semver-major"