version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "Ivanbyone"
    labels:
      - "dependencies" 
    commit-message:
      prefix: "chore(deps)"